transformer:
  encoder_layer: 4
  encoder_head: 2
  encoder_hidden: 256
  decoder_layer: 6
  decoder_head: 2
  decoder_hidden: 256
  ffn_kernel_size: 9
  encoder_dropout: 0.0 #0.1
  decoder_dropout: 0.0 #0.1
  ffn_padding: "SAME"
  ffn_act: "gelu"

denoiser:
  denoiser_hidden: 512
  denoiser_dropout: 0.0 #0.2
  residual_layers: 20
  residual_channels: 512
  noise_schedule_naive: "cosine"
  noise_schedule_shallow: "linear"
  timesteps: 100
  K_step: 100
  max_beta: 0.06
  s: 0.008
  keep_bins: 128

variance_predictor:
  filter_size: 256
  predictor_grad: 0.1
  predictor_layers: 2
  predictor_kernel: 5
  cwt_hidden_size: 128
  cwt_std_scale: 0.8
  dur_predictor_layers: 2
  dur_predictor_kernel: 3
  dropout: 0.5

variance_embedding:
  use_pitch_embed: True
  pitch_n_bins: 300
  use_energy_embed: False
  energy_n_bins: 256
  energy_quantization: "linear" # support 'linear' or 'log', 'log' is allowed only if the energy values are not normalized during preprocessing

multi_speaker: True
n_speakers: 10
max_seq_len: 1000

vocoder:
  model: "HiFi-GAN" # support 'HiFi-GAN', 'MelGAN'
  speaker: "universal" # support    'LJSpeech', 'universal'

dataset: "base_ds"

preprocessing:
  val_size: 512
  text:
    text_cleaners: ["english_cleaners"]
    language: "en"
  audio:
    sampling_rate: 44100
    max_wav_value: 32768.0
  stft:
    filter_length: 2048
    hop_length: 512
    win_length: 2048
  mel:
    n_mel_channels: 128
    mel_fmin: 40
    mel_fmax: 16000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    pitch_type: "cwt" # support 'frame', 'ph', 'cwt'
    pitch_norm: "log" # support 'standard', 'log'
    pitch_norm_eps: 0.000000001
    pitch_ar: False
    with_f0: True
    with_f0cwt: True
    use_uv: True
    f0_mean: 214.31683793057
    f0_std: 63.97520977575229
    cwt_scales: -1
  energy:
    feature: "frame_level" # support 'phoneme_level' or 'frame_level'
    normalization: True

train_path:
  ckpt_path: "./output/ckpt/"
  log_path: "./output/log/"
  result_path: "./output/result/"

path:
  raw_path: "./dataset_raw/base_ds"
  preprocessed_path: "./dataset/base_ds"
  train_filelist: "filelists/train.txt"
  val_filelist: "filelists/val.txt"

optimizer:
  batch_size: 8
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1
  grad_acc_step: 1
  warm_up_step: 2000
  anneal_steps: [50000, 100000, 150000]
  anneal_rate: 0.5
  init_lr: 0.0005
loss:
  noise_loss: "l1"
  dur_loss: "mse"
  pitch_loss: "l1"
  cwt_loss: "l1"
  # cwt_add_f0_loss: false
  lambda_f0: 1.0
  lambda_uv: 1.0
  lambda_ph_dur: 1.0
  lambda_word_dur: 1.0
  lambda_sent_dur: 1.0
step:
  total_step_aux: 160000
  total_step_naive: 160000
  total_step_shallow: 320000
  log_step: 100
  synth_step: 1000
  val_step: 1000
  save_step: 200
